--- #YAML:1.0
name:                Algorithm-NeedlemanWunsch
version:             0.03
abstract:            sequence alignment with configurable scoring
license:             ~
author:              
    - Vaclav Barta <vbar@comp.cz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    List::Util:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
