---
abstract: 'sequence alignment with configurable scoring'
author:
  - 'Vaclav Barta <vbar@comp.cz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-NeedlemanWunsch
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  List::Util: 0
  Test::More: 0
version: 0.04
